### ISSUE TITLE
Is the Comment Extension Already Usable?

### ISSUE THREAD

**Issue by ghost** [mecha-cms/extend.comment#1]
Hi @tovic,

I'm assuming that you have not finished this comment extension yet. In the backend is still "Coming Soon" and I have inserted the line code in the page.php, but no comment form is displayed yet.

I'm waiting for your early feedback and if the comments are completely finished, then I do not need any more disqus.

**Comment by taufik-nurrohman** [comment]
Test comment on my site first, then try it by your self&hellip;

&rarr; http://mecha-cms.com/reference/extension/plugin/comment-notify

You may need to update the core CMS too. Backend view of this extension becomes the second priority for now (it is a bit complicated to generate the proper view as the comment feature can be used on any pages, on any folders). To manage comments manually, go to `.\lot\comment` folder from _cPanel_.

**Comment by taufik-nurrohman** [comment]
I have a [folder permission problem](https://github.com/mecha-cms/extend.comment/commit/c94b500956dca16c4be63b022bd157ec51e47824) recently. Please check your `.\lot\comment` folder permission if you thought that you can publish a comment but do not see any comments added to the page (just a success message). The folder permission should be `755`.

![2017-04-07_010029](https://cloud.githubusercontent.com/assets/1669261/24769508/00645a2a-1b31-11e7-83af-b205a67c651d.png)

**Comment by ghost** [comment]
Thanks for these tips. I've done everything, and now the comments are immediately visible after I create them.

1. Will it still be possible for my readers to subscribe to the comments by e-mail? That would be very interesting for the blog itself.

2. Why do not you rely on Captcha protection for spam or ReCaptcha? Have you already thought in the direction?

Thanks in advance.

**Comment by taufik-nurrohman** [comment]
> Will it still be possible for my readers to subscribe to the comments by e-mail? That would be very interesting for the blog itself.

I have no idea on how to do it. Need to learn it from another CMS.

> Why do not you rely on Captcha protection for spam or ReCaptcha? Have you already thought in the direction?

Will be available as a plugin. BTW, you already have a simple spam filter that is, by blacklisting some bad words including email addresses with the `config.php` file:

~~~ .php
<?php

return [
    …
    …
    …
    'query_x' => ['some', 'bad', 'words', 'goes', 'here', 'you.can.black.list@email.too']
];
~~~

**Comment by ghost** [comment]
Ok, thank you for your replies. But it is already good, because I have been waiting for the comment system all the time :smile: And now it is available!

Well, then it will be a Captcha plugin. Should work well and spam will give, as the Internet is so.
