### ISSUE TITLE
Invalid `?parent` query string generates a new empty comment

### ISSUE THREAD

**Issue by salimromadhon** [mecha-cms/extend.comment#3]
**Describe the bug**

In a page with configuration:
- comment fully enabled (type 1) or
- new comment disabled (type 2)

When I visit the page with `?parent` value refers to invalid existing parent, it generates an empty comment using the value.

**Expected behavior**

It should check if the parent actually exists, and ignore if it doesn't.

**Environment**

Mecha v2.4.0 and comment extension v1.19.0.

**Comment by taufik-nurrohman** [comment]
Thanks for the report! Now finally I know why there are some empty comment files generated in my web storage.
